dist: trusty
sudo: false
language: python
env:
- TOXENV=flake8
- TOXENV=isort
cache: pip
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TOXENV=py27-1.11
  - python: 3.4
    env: TOXENV=py34-1.11
  - python: 3.4
    env: TOXENV=py34-2.0
  - python: 3.5
    env: TOXENV=py35-1.11
  - python: 3.5
    env: TOXENV=py35-2.0
  - python: 3.5
    env: TOXENV=py35-2.1
  - python: 3.5
    env: TOXENV=py35-master
  - python: 3.6
    env: TOXENV=py36-1.11
  - python: 3.6
    env: TOXENV=py36-2.0
  - python: 3.6
    env: TOXENV=py36-2.1
  - python: 3.6
    env: TOXENV=py36-master
  - python: 3.7
    env: TOXENV=py37-2.0
    dist: xenial
    sudo: true
  - python: 3.7
    env: TOXENV=py37-2.1
    dist: xenial
    sudo: true
  - python: 3.7
    env: TOXENV=py37-master
    dist: xenial
    sudo: true
  allow_failures:
  - env: TOXENV=py35-master
  - env: TOXENV=py36-master
  - env: TOXENV=py37-master
install:
- pip install tox coveralls
script:
- tox
after_success:
- if [ -f .coverage ]; then coveralls; fi
before_deploy: "pip install django"
deploy:
  provider: pypi
  user: charettes
  password:
    secure: "K9pNtqnPc7yiCsZp9DpudUmlaKgPNWmns1HvCskNbFhmTxja7omn0xl/a1tbH7sUsbFcDctEZDd2IRer033aYICHGhskShBjPyOCX0TWyJUlrNiovkrcqy8dc36udTJ53FVgxYwCPQ/2AZq7Prw6ya71kw2jPV4Mklqyb6sKxRM="
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV = py27-1.11"
